Execute transaction
fractal-framework/fractal-interface pull request #114
Opened 2022-04-29 21:45 UTC by tbwebb22

This PR adds functionality to support executing a proposal that has been passed and queued.

This includes:
 - A ProposalExecute component that gets rendered on the ProposalDetailed component when the proposal is able to be executed
 - Adding a proposal eta parameter to the proposal data object for checking whether a proposal is able to be executed
 - A useExecuteTransaction hook that handles the execute transaction

![image](https://user-images.githubusercontent.com/84364476/166072947-ff81238c-2193-4f12-ad01-e8916a7c4ea9.png)

2022-04-30 02:36 UTC, adamgall requested changes

2022-04-30 02:36 UTC, adamgall commented on src/hooks/useBlockNumber.ts
> +    return () => clearInterval(timer);
I don't think you'd want to set a timer in here, especially not one that fires every second, since blocks show up on average like 12-15 seconds.

You can set an event listener on the `provider` to get notified when blocks come in.

Lil something like this: https://github.com/decent-labs/decent-token-vesting/blob/master/src/data/time.ts#L4

2022-04-30 02:36 UTC, adamgall commented on src/hooks/useBlockTimestamp.ts
> +  const [blockTimestamp, setBlockTimestamp] = useState<number>();
Perhaps the initial state of this should be Javascript's time, so there isn't that moment at the start of the app where time is undefined.

2022-04-30 02:36 UTC, adamgall commented on src/hooks/useBlockTimestamp.ts
> +      setBlockTimestamp(undefined);
Perhaps the initial state of this should be Javascript's time, so there isn't that moment at the start of the app where time is undefined.

2022-04-30 02:36 UTC, adamgall commented on src/hooks/useBlockTimestamp.ts
> +    return () => clearInterval(timer);
Seems overkill to make this `getBlock` network request every second. Perhaps, every second you just increase the current time by 1 second, and let the `blockNumber` updating be your trigger to make that network request to get the new block's timestamp.

Right now, the app will only "know what time it is" on the order of every block updating the time by like 15 seconds at a time. The way I described above, the app could count up second by second, and "realign" itself with every block.

Something like this: https://github.com/decent-labs/decent-token-vesting/blob/master/src/data/time.ts#L32

2022-04-30 02:36 UTC, adamgall commented on src/hooks/useBlockTimestamp.ts
> +    return () => clearInterval(timer);
I would also recommend you move these hooks into the global data layer, so that if multiple components need to know the time, this code and these network requests and listeners are only instantiated once.

2022-04-30 02:36 UTC, adamgall commented on src/daoData/useProposals.ts
> +) => {
I know nothing really changed here, but perhaps this function could be turned into a hook and placed into the `hooks` directory. It could then use the `useWeb3` hook to grab the `provider` so that could be removed from the input params.

2022-04-30 02:36 UTC, adamgall commented on src/components/DAOs/DAO/Proposals/ProposalExecute.tsx
> +      return;
`setShow(false)` before return to reset the default state here please.

2022-04-30 02:36 UTC, adamgall commented on src/components/DAOs/DAO/Proposals/ProposalExecute.tsx
> +    }
`else { setShow(false) }`

or

`setShow(proposal.eta !== 0 && proposal.eta < blockTimestamp)`

2022-04-30 02:36 UTC, adamgall commented on src/components/DAOs/DAO/Proposals/ProposalExecute.tsx
> +}
Is there no indication to the user that a proposal has _already_ been executed?

2022-05-02 14:28 UTC, adamgall commented
Please also add relevant Issues to this PR

2022-05-02 17:07 UTC, tbwebb22 commented on src/hooks/useBlockTimestamp.ts
> +    return () => clearInterval(timer);
Why would we want to increment the time every second, ultimately all we care about is the timestamp of the last mined block, since that determines when state has updated last, correct?

2022-05-02 17:59 UTC, adamgall commented on src/hooks/useBlockTimestamp.ts
> +    return () => clearInterval(timer);
I'm just trying to think ahead a bit.

It might be good for the webapp to have a clock that _does_ increment every second.

Imagine the scenario:

* blocks come every 15 seconds
* block `n` is mined _right now_, timestamp is 100
* there's a proposal that _can be_ executed at timestamp 105
* if all we do is look at last block's timestamp, then the webapp won't allow user to make the transaction until block `n + 1` is mined (at timestamp 115), and the earliest block that transaction will get into is block `n + 2` (at timestamp 130).
* if we optimistically keep track of the time per second, the transaction button will enable at timestamp 105, user makes transaction, it could get into block `n + 1` (timestamp 115)

2022-05-02 18:16 UTC, tbwebb22 commented on src/components/DAOs/DAO/Proposals/ProposalExecute.tsx
> +}
If a proposal has already been executed, then this component should just return null.
However, the proposal state will be updated to "Executed" and shown on the Proposal Detail card.

2022-05-02 18:54 UTC, adamgall commented on src/daoData/useProposals.ts
> +) => {
ignore this, too complicated for now

2022-05-02 19:56 UTC, tbwebb22 commented on src/hooks/useBlockTimestamp.ts
> +    return () => clearInterval(timer);
Updated hook to increment time every second, and still get timestamp updates as new blocks are found

2022-05-02 21:12 UTC, adamgall approved these changes

2022-05-02 21:12 UTC, adamgall commented on src/daoData/daoData.ts
> +    currentBlockNumber,
This `currentBlockNumber` property probably doesn't (yet) need to be included in the exported data object (don't think it's being used in any components), but it's not doing any harm.

2022-05-02 21:13 UTC, merged