updates TokenDetails input validations
fractal-framework/fractal-interface pull request #133
Opened 2022-05-02 19:58 UTC by Da-Colon

## Overview
- adds `isWholeNumber` prop to string to prevent chars other than numbers
- adds props to allow for input customization if needed
- updates tokenSupply validation
- updates token allocation validation to happen individually on Change

## Screenshots
![image](https://user-images.githubusercontent.com/38386583/166314959-7bf566e3-120a-4362-87be-b4cf73d1de4b.png)

2022-05-02 21:16 UTC, adamgall requested changes
Super small lil thang.

Other than this, I haven't given the PR a very thorough review, I'm sorry.

I figure, this seems like enough of a solid move in the right direction that any other tweaks we'll learn about from future usage. I want to just keep the merge cadence high right now.

2022-05-02 21:16 UTC, adamgall commented on src/components/DAOs/New/TokenAllocationInput.tsx
> +        containerClassName="col-start-1 col-helperspan-4 md:col-span-5 w-full"
`col-helperspan-4`?

2022-05-02 21:19 UTC, adamgall approved these changes

2022-05-02 21:19 UTC, merged

2022-05-03 13:46 UTC, sethhrbek commented on src/hooks/useAddress.ts
> +export const checkAddress = async (provider: any, addressInput?: string): Promise<boolean> => {
could this be `isAddressValid`? `check` feels a little vague (also not sure if this app follows the `is`/`has` pattern for booleans).

2022-05-03 13:46 UTC, sethhrbek commented on src/hooks/useAddress.ts
> +    return true;
Could this be `return !!resolvedAddress`

2022-05-03 13:46 UTC, sethhrbek commented on src/hooks/useAddress.ts
> +  }
If you don't need to check provider, this case and previous case could be combined to just 

```
if (!addressInput) {
    return false;
  }
```

A an empty string with spaces `"   "` will return false with the `ethers.utils.isAddress` call.

2022-05-03 13:46 UTC, sethhrbek commented on src/components/DAOs/New/TokenDetails.tsx
> +        <Input type="text" value={symbol} onChange={onTokenChange} label="Token Symbol" helperText="Max: 5 characters" disabled={false} />
Should `InputProps` have a `max` field added to set this to `5`? or is that handled somewhere else?

2022-05-03 13:46 UTC, sethhrbek commented on src/components/DAOs/New/TokenDetails.tsx
> +            return setError(index, tokenAllocation, "Invalid address");
would it be beneficial to type these error strings into their own constants in case the app needs to check them elsewhere in the app? I.e. `if (error === INVALID_ADDRESS) do something`

2022-05-03 13:46 UTC, sethhrbek commented on src/components/DAOs/New/TokenDetails.tsx
> +    if (!tokenAllocations || !provider) return;
In the other `useEffect` in this file, `tokenAllocations` is explicitly checked for `undefined` -- is there a reason the check here is different?

2022-05-03 14:18 UTC, sethhrbek commented on src/hooks/useAddress.ts
> +    return true;
I see a lot of "return true" / "return false" as opposed to things like `return !!myVar` in the app, in which case if that is the pattern can ignore this comment