Create proposal
fractal-framework/fractal-interface pull request #38
Opened 2022-04-15 19:26 UTC by tbwebb22

2022-04-18 13:42 UTC, adamgall commented
@christopherdancy when you have time today, can you please have the first go at doing code review on this PR?

just come at it from the point of view of "what would Adam's stickler-ass say"

2022-04-18 14:46 UTC, adamgall commented
@tbwebb22 please link this PR with the appropriate Issue

2022-04-19 17:13 UTC, christopherdancy reviewed
Please review @adamgall

2022-04-19 17:13 UTC, christopherdancy commented on src/components/DAOs/DAO/CreateProposal/Essentials.tsx
> +      <CreateDAOInput
More General Component Naming

2022-04-19 17:13 UTC, christopherdancy commented on src/components/DAOs/DAO/CreateProposal/Essentials.tsx
> +      <CreateDAOInput
i.e- multistepInput

2022-04-19 17:13 UTC, christopherdancy commented on src/components/DAOs/DAO/CreateProposal/Transaction.tsx
> +  const updateParameters = (parameters: string) => {
This makes sense. If there are multiple transactions. a user can update anyone of them.

2022-04-19 17:13 UTC, christopherdancy commented on src/components/DAOs/DAO/CreateProposal/index.tsx
> +export type TransactionData = {
Could this be a type on the transactions component which is pulled in to this component for types?

2022-04-19 17:13 UTC, christopherdancy commented on src/components/DAOs/DAO/CreateProposal/index.tsx
> +        targetAddress: "",
There should be state checking for each input.  Check below for an example found in DAODetails.tsx

`  useEffect(() => {
    setNextEnabled(name !== undefined && name.trim() !== "")
  }, [name, setNextEnabled]);`

2022-04-19 17:13 UTC, christopherdancy commented on src/components/DAOs/DAO/CreateProposal/index.tsx
> +          {step === 0 && (
Review stepDisplay component on CreateDAO/index.tsx. Creating a component would be cleaner

2022-04-19 17:44 UTC, adamgall requested changes
Just some small changes. Biggest thing is related to RESTful routing

2022-04-19 17:44 UTC, adamgall commented on src/components/DAOs/DAO/index.tsx
> +      <Route path="createproposal" element={<CreateProposal address={params.address} />} />
@tbwebb22

to keep these routes RESTful (and give some "breathing room" for the immediate next work to come with the "proposals" work), the route for this should be `/daos/:address/proposals/new`

So, can you create a directory in the tree for `Proposals`, with an `index.tsx` that defines the routes (with just `new` for now), and a directory in there called `New` containing evrything that's currently in the `CreateProposal` directory? Basically, follow the pattern that the DAO directory has started.

Thanks!

2022-04-19 17:44 UTC, adamgall commented on src/components/DAOs/DAO/Summary.tsx
> +        <Link to="details" className="underline">DAO Details</Link>
nitpick: please make sure things are indented properly in here

2022-04-19 17:44 UTC, adamgall commented on src/components/DAOs/DAO/CreateProposal/Transaction.tsx
> +  };
Wondering if there's a way to DRY up these functions. Not asking anything of you here, just typing out loud.

2022-04-19 18:43 UTC, tbwebb22 commented
@adamgall Addressed these comments in recent commits

2022-04-19 18:58 UTC, adamgall requested changes
Looks great @tbwebb22 , thank you. One small change then we'll merge.

2022-04-19 18:58 UTC, adamgall commented on src/components/DAOs/DAO/Proposals/index.tsx
> +      <Route index element={<New address={address} />} />
@tbwebb22 just remove this line for now plz. Let's not render the `new` components unless `/new` is in the URL

2022-04-19 19:01 UTC, adamgall approved these changes
Noice

2022-04-19 19:03 UTC, merged