Style search
fractal-framework/fractal-interface pull request #58
Opened 2022-04-26 18:15 UTC by christopherdancy

<img width="946" alt="image" src="https://user-images.githubusercontent.com/69045872/165365211-355aa073-ae3e-4991-bca4-c47901be0107.png">

<img width="946" alt="image" src="https://user-images.githubusercontent.com/69045872/165365270-471f8794-716d-4301-a3dc-034f43f2d706.png">

<img width="946" alt="image" src="https://user-images.githubusercontent.com/69045872/165365486-e0c5fed0-e506-469c-932b-a036abe02603.png">

2022-04-26 18:39 UTC, adamgall requested changes

2022-04-26 18:39 UTC, adamgall commented on src/components/DAOs/Search/DAOSearch.tsx
> +            }
can be written as

```
{ searchFailed === false && (
  <p className="text-gray-50 pt-1 text-sm">Use a valid Fractal ETH address or ENS domain</p>
)}
```

2022-04-26 18:39 UTC, adamgall commented on src/components/DAOs/Search/DAOSearch.tsx
> +                  className="px-6 py-1 mx-2 border border-gold-500 rounded bg-gold-500 text-black-300 capitalize"
Can this button (basically, its styling) be abstracted up the tree, so that it can be reused?

I anticipate that this app will settle upon a handful of different "looks" for buttons, and those styles should only be implemented once.

Styling a button like this, within another component, means that if we want a similar looking button elsewhere it will need to be re-styled elsewhere too.

2022-04-26 18:39 UTC, adamgall commented on src/components/DAOs/Search/DAOSearch.tsx
> +            }
but actually... see the engulfing comment

2022-04-26 18:39 UTC, adamgall commented on src/components/DAOs/Search/DAOSearch.tsx
> +        </InputBox>
Seems like there are two different components that are responsible for displaying the text beneath `InputAddress` component.

That seems messy. It makes it harder to get the styles/spacing consistent (see the little sizing/spacing jumps that happen when you first search for an invalid DAO), and puts multiple "things" in charge of one "thing".

Please consolidate this logic into one place. For example, what I would do, is move _all_ of the text display into the `Search` (and then `SearchingDAO`) component.

2022-04-26 18:40 UTC, adamgall commented
@christopherdancy also please attach whatever relevant issues to this PR

2022-04-27 13:41 UTC, adamgall commented on src/components/ui/SearchButton.tsx
> +export default SearchButton;
Much closer, but still some conceptual problems here with "reusability".

First, you've named this component `SearchButton`, and hardcoded the word "search" into it. The intention with my previous request was to make it so that this "flavor" of button (meaning really just the colors and borders etc) could be reused anywhere in the app, regardless of what that button functionally represents in that context.

Next, the outer wrapping `div` with a left margin seems out of place. That's an assumption relating to "how this button is placed next to other elements" that I don't think this Button should make.

Look at the `Button.tsx` component. It makes no assumption about how it's being used, or the label on it, or how it should exist next to other components.

Perhaps move the `SearchButton` code into this existing `Button` component, and export multiple "flavors" of buttons from this file.

See https://github.com/decent-labs/decent-token-vesting/blob/master/src/components/ui/Input.tsx for an example from another project in which I did this for `input` components. There's a "base" `Input` component which isn't even exported, but implements functionality that all of the different "flavors" of inputs will use. Flavors in this "input" context represent inputting numbers, addresses, token amounts.

Something like that is what I'm looking for here.

2022-04-27 13:43 UTC, adamgall commented on src/components/ui/InputAddress.tsx
> +export default InputAddress
Please move this component into the existing `Input.tsx` file.

2022-04-27 13:45 UTC, adamgall commented on src/components/ui/Input.tsx
> +      className={`${width} border ${borderColor} border-gray-20 bg-gray-400 rounded py-1 px-2 shadow-inner text-gray-50 ${disabled ? "disabled" : ""}`}
Don't make `width` be an input to this component. Always make the `input` extend to fill its container. If you want to constrain the width of an `Input`, then do so at the place where it's being used (by, for example, wrapping the input in a `div` and giving that a width).

2022-04-27 13:50 UTC, adamgall commented on src/components/DAOs/Search/SearchingDAO.tsx
> +  if (loading !== true && searchAddress === undefined || searchAddress === "") {
Warnings on this line, please use parentheses to make order of operations explicit

2022-04-27 13:55 UTC, adamgall commented on src/components/DAOs/Search/SearchingDAO.tsx
> +      <p className="text-gray-50 pt-1 text-sm">Use a valid Fractal ETH address or ENS domain</p>
There is still some spacing consistency issues as the text changes from this `p` tag, to the `SearchError` component.

2022-04-27 15:55 UTC, christopherdancy commented on src/components/ui/SearchButton.tsx
> +export default SearchButton;
With a new standard being developed by Taylor. This should be handled in a separate PR to keep consistency.

2022-04-27 16:02 UTC, adamgall commented on src/components/DAOs/Search/SearchingDAO.tsx
> +  if (loading !== true && searchAddress === undefined || searchAddress === "") {
@christopherdancy this is still a warning in the Typescript compiler

2022-04-27 16:04 UTC, christopherdancy commented on src/components/DAOs/Search/SearchingDAO.tsx
> +  if (loading !== true && searchAddress === undefined || searchAddress === "") {
for some reason I am not getting this error. Did you restart typescript server?

2022-04-27 16:09 UTC, merged