Header Dropdown update
fractal-framework/fractal-interface pull request #71
Opened 2022-04-27 21:46 UTC by Da-Colon

## Overview
Adds and Updates components required for Header Wallet and Menu Updates

- Adds Dropdown when not connected
- Adds External Links to Menu
- Updates Menu with icons and colors to match figma

## Notes
- I did end up moving `components/Header.tsx` -> `Header/index.tsx`. if your IDE or current React session is giving you trouble with the switch just restart IDE and run `npm run start` again. (This should be a problem at all, it sometimes can happen though with this kind of update)

- left a `@todo` for FAQ link to be updated when it's available

## Screenshots
![image](https://user-images.githubusercontent.com/38386583/165635863-c86a1471-e1ad-40a2-bb49-e8601d6bc9ec.png)

![image](https://user-images.githubusercontent.com/38386583/165635925-bbeea8b0-121c-4b4d-8986-ca82dfe9bb4e.png)

Menu Item Hover State
- Address Menu Item does not have this effect.

![Fractal 🔊 2022-04-27 17-43-04](https://user-images.githubusercontent.com/38386583/165636284-d25e8232-9175-434a-bee4-86024397b5b0.png)

2022-04-27 21:55 UTC, Da-Colon commented
One thing for another PR might be a good idea for a toast message when a user clicks 'copy'. if agreed I can add a task for that.

2022-04-27 22:11 UTC, adamgall commented
> One thing for another PR might be a good idea for a toast message when a user clicks 'copy'. if agreed I can add a task for that.

Yes sir please sir, good idea sir. I noticed that yesterday but forgot to open an issue for it.

2022-04-28 15:01 UTC, christopherdancy commented on src/components/ui/Header/MenuItems.tsx
> +  title: "Contract",
This is spelled contract instead of contact. Spelling error.

2022-04-28 15:06 UTC, christopherdancy commented on src/components/ui/Header/MenuItems.tsx
> +  // @todo add link for FAQ
Should this be completed on a future PR?

2022-04-28 15:32 UTC, Da-Colon commented on src/components/ui/Header/MenuItems.tsx
> +  // @todo add link for FAQ
Current there is not FAQ available I can remove the field (comment out) until it's available.

2022-04-28 16:51 UTC, adamgall requested changes
@da-colon As discussed on call:

- [x] Make entire top-right area "open the menu"
- [x] When wallet is connected, make top item in dropdown (the user's address) a clickable `EtherscanLink`
  - [x] make sure it's the gold link color plz
- [x] Make entire menu item area clickable
- [x] Don't use custom "display name" on etherscan links
- [ ] monospace the address
- [ ] Use a bigger down arrow

2022-04-28 23:43 UTC, adamgall approved these changes
Looks great thank you @Da-Colon

2022-04-28 23:44 UTC, merged