Cast votes
fractal-framework/fractal-interface pull request #80
Opened 2022-04-28 19:51 UTC by tbwebb22

This PR includes:
 - A new CastVote component that is rendered on the ProposalDetails page which allows a user to vote on an open proposal
 - The CastVote component only allows a user to vote if the proposal is open, and they have not already voted
 - The CastVote component shows a user what their vote was if they have already voted on the proposal
 - A useCastVote hook that handles the transaction
 - Additional hooks in useProposals which handles getting the user vote data

The styling of the CastVote component should be refined in a future PR

![image](https://user-images.githubusercontent.com/84364476/165834355-7d5f34b8-dc4a-469b-b95b-89d62c440142.png)

2022-04-28 20:40 UTC, adamgall requested changes

2022-04-28 20:40 UTC, adamgall commented on src/components/DAOs/DAO/Proposals/CastVote.tsx
> +    if(proposal.stateString === "Closed") {
might be less error prone (in the future, as we localize this app) to use the `state` instead of `stateString` to do comparison here.

2022-04-28 20:40 UTC, adamgall commented on src/components/DAOs/DAO/Proposals/DelegateVote.tsx
> +export default DelegateVote;
Should this file be here? It's not being referenced anywhere else in this PR.

2022-04-28 20:40 UTC, adamgall commented on src/components/DAOs/DAO/Proposals/ProposalDetails.tsx
> +      <CastVote proposal={proposal} />
Can you please try to make this look more like the rendering?

It should be below the Proposal Details
The font in the buttons is wrong
The arrow should be right aligned
There shouldn't be lines between all of the buttons
etc

<img width="996" alt="Screen Shot 2022-04-28 at 4 23 04 PM" src="https://user-images.githubusercontent.com/706929/165839733-7ef78e7a-e9c0-4662-a7ad-21e3cff12767.png">

2022-04-28 20:40 UTC, adamgall commented on src/daoData/useDeployDAO.ts
> +          abiCoder.encode(["uint256"], [BigNumber.from("0")]), // voteDelay - 1 day was 6545 blocks
What's the significance of this changing from "6545" to "0"?

2022-04-28 20:40 UTC, adamgall commented on src/components/DAOs/DAO/Proposals/CastVote.tsx
> +      <ConnectModal />
There is going to be an effort soon to get rid of the full screen semi-transparent modal things, so let's just remove it from here now.

2022-04-28 20:40 UTC, adamgall commented on src/components/DAOs/DAO/Proposals/CastVote.tsx
> +      <ConnectModal />
Same with that Connect Modal

2022-04-28 20:40 UTC, adamgall commented on src/components/ui/SelectVoteButton.tsx
> +export default SelectVoteButton;
I'd love to see this custom button inherit from a more global Button that has global styles defined.

2022-04-28 20:40 UTC, adamgall commented on src/components/ui/SelectVoteButton.tsx
> +      {selected ? <Check /> : null}
Can be written as

```
{selected && <Check />}
```

2022-04-28 20:40 UTC, adamgall commented on src/daoData/useProposals.ts
> +        userVote: userProposalVote ? userProposalVote.vote : undefined,
Much like `state` and `stateString`, probably a good idea to have `userVote` and `userVoteString` here.

Elsewhere I saw some logic that is checking the value of `userVote` to do things (ex: line 43 of CastVote.tsx), and it's not very future proof (for when we go and localize this app). Better to use actual data for comparisons, and english strings (in the future, any language strings) _just_ for display purposes.

2022-04-28 20:41 UTC, adamgall requested changes
Forgot to mention in preview review, please merge `master` into this branch

2022-04-28 20:46 UTC, adamgall requested changes

2022-04-28 20:46 UTC, adamgall commented on src/components/DAOs/DAO/Proposals/CastVote.tsx
> +          disabled={newVote === undefined || proposal.stateString !== "Open" || proposal.userVote !== undefined}
I was able to cast a vote, even though I had no tokens and my votes weren't delegated anywhere.

Apparently the contracts just let it happen without reverting the transaction.

But, our UI should be smarter than that.

Please only make sure this button (probably all the buttons) has additional checks to only allow them to be interactive if it makes sense for that user.

2022-04-28 21:07 UTC, tbwebb22 commented on src/components/DAOs/DAO/Proposals/DelegateVote.tsx
> +export default DelegateVote;
Nope, that shouldn't have been there. Fixed

2022-04-28 21:08 UTC, tbwebb22 commented on src/daoData/useDeployDAO.ts
> +          abiCoder.encode(["uint256"], [BigNumber.from("0")]), // voteDelay - 1 day was 6545 blocks
This changes it so that we can vote on a newly created proposal immediately instead of waiting a day, for testing purposes.

2022-04-28 21:09 UTC, tbwebb22 commented on src/daoData/useDeployDAO.ts
> +          abiCoder.encode(["uint256"], [BigNumber.from("0")]), // voteDelay - 1 day was 6545 blocks
Of course we will want to change this back for prod

2022-04-28 21:13 UTC, adamgall commented on src/daoData/useDeployDAO.ts
> +          abiCoder.encode(["uint256"], [BigNumber.from("0")]), // voteDelay - 1 day was 6545 blocks
Should (could?) this be a user input when making a new Proposal?

Or

Why not leave it at "no delay" on mainnet?

2022-04-28 21:14 UTC, tbwebb22 commented on src/components/DAOs/DAO/Proposals/CastVote.tsx
> +      <ConnectModal />
Removed both

2022-04-28 22:38 UTC, tbwebb22 commented on src/components/DAOs/DAO/Proposals/CastVote.tsx
> +          disabled={newVote === undefined || proposal.stateString !== "Open" || proposal.userVote !== undefined}
Updated so that user cannot vote if they have a vote power of 0 for this proposal

2022-04-29 01:45 UTC, tbwebb22 commented on src/daoData/useDeployDAO.ts
> +          abiCoder.encode(["uint256"], [BigNumber.from("0")]), // voteDelay - 1 day was 6545 blocks
This parameter is specific to the Governor module, so it can't be changed per proposal. 

We could leave it at no delay on mainnet for sure. I think it could be argued though that its good to have a delay between when a proposal is created and voting can begin.

2022-04-29 01:54 UTC, tbwebb22 commented on src/components/DAOs/DAO/Proposals/ProposalDetails.tsx
> +      <CastVote proposal={proposal} />
Update styling according to new screen from design team:

Current styling:
![image](https://user-images.githubusercontent.com/84364476/165873907-b0f547f0-fd69-49cc-8d69-b84b9ccfab15.png)

Design team screen:
![image](https://user-images.githubusercontent.com/84364476/165873981-4391126c-6b94-4cad-b51d-5768a263d3cb.png)

2022-04-29 12:59 UTC, adamgall commented on src/components/DAOs/DAO/Proposals/ProposalDetails.tsx
> +      <CastVote proposal={proposal} />
Looking much better thank you.

First thing that stands out is that the "Cast Vote" and "Results" components should definitely be sharing some container-level styling (so that the title and horizontal line are on the same latitude.

But we can tackle that in a later PR. Let's get this merged.

2022-04-29 13:23 UTC, adamgall approved these changes

2022-04-29 13:23 UTC, adamgall commented on src/daoData/useDeployDAO.ts
> +          abiCoder.encode(["uint256"], [BigNumber.from("0")]), // voteDelay - 1 day was 6545 blocks
ohhh i'm sorry, i didn't realize this was in the `useDeployDAO` hook. so this happens when a DAO is deployed. got it.

then I ask one more thing here. throw the comment `TODO: set back to 6545 before mainnet` in here.

So that we can search the codebase for `TODO` later and deal with things.

2022-04-29 13:23 UTC, adamgall commented on src/components/DAOs/DAO/Proposals/ProposalDetails.tsx
> +      </div>
I was expecting this to look cramped on mobile... but honestly it't not too bad!

2022-04-29 13:23 UTC, adamgall commented on src/components/DAOs/DAO/Proposals/CastVote.tsx
> +            proposal.userVotePower.eq(0)
Extract this out to a function (or better, some react state :)) cause it's the same for all buttons.

edit: ah fuck it let's just leave as is for now and handle later

2022-04-29 13:23 UTC, adamgall commented on src/components/DAOs/DAO/Proposals/CastVote.tsx
> +            proposal.userVotePower.eq(0)
In a future PR, let's give some TLC to concepts across the data layer around "when should things be able to be `undefined`"

2022-04-29 13:23 UTC, merged